apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: suxess-it-qa
  labels:
    app: demo
    backstage.io/kubernetes-id: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        backstage.io/kubernetes-id: demo
    spec:
      containers:
#      - image: quay.io/rbaumgar/monitor-demo-app-jvm
      - image: quay.io/rbaumgar/monitor-demo-app-jvm
        imagePullPolicy: Always
        name: demo