apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: suxess-it-qa
  labels:
    app: demo
    backstage.io/kubernetes-id: demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  type: ClusterIP